name: "📚 latest Blog"

on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *" # Runs Every min

jobs:
  update_blogs:
    name: "Update With Latest Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@1.1.1"
        with:
          USERNAME: "ndrohith09" # Hashnode Username
          COUNT: 5 # MAX Visisble
          STYLE: "blog-left"
          BLOG_URL: "https://ndrohith09.hashnode.dev/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
